env-local:
	@rm .env
	@echo "API_PORT=3000" >> .env
	@echo "AWS_ACCESS_KEY=abcde" >> .env 
	@echo "AWS_DYNAMO='http://localhost:18000'" >> .env
	@echo "AWS_SECRET_KEY=abcde" >> .env
	@echo "BATTLE_TABLE=Battles" >> .env
	@echo "SESSION_TABLE=Sessions" >> .env
	@echo "API_ENV=LOCAL" >> .env
	@echo "API_PREFIX=" >> .env
	@cat .env 
